# Generated by Django 6.0.7 on 2026-09-11 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Suppression de `Subject`. IRREVERSIBLE SUR UNE BASE PEUPLEE.

    Django sait ecrire le sens arriere (les `RemoveField` se reinversent en
    `AddField`), mais le resultat ne s'applique pas : reinstaller
    `Result.subject` / `Round.subject`, deux FK NOT NULL, echoue sur PostgreSQL
    des que les tables ne sont pas vides — et 0011 est un `noop` en face, donc
    rien ne repeuplerait ces colonnes ensuite. Le test de migration ne traverse le
    sens arriere que sur une base vide : il ne dit RIEN de ce cas.

    En prod, revenir en arriere = restaurer une sauvegarde anterieure a 0010, pas
    `migrate rooms 0011`.
    """

    dependencies = [
        ('rooms', '0011_subjects_to_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='room',
        ),
        migrations.RemoveField(
            model_name='result',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='round',
            name='subject',
        ),
        migrations.AlterField(
            model_name='result',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='rooms.item'),
        ),
        migrations.AlterField(
            model_name='result',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='rooms.round'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.UniqueConstraint(fields=('round', 'item'), name='uniq_result_round_item'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
