# Generated by Django 6.0.7 on 2026-09-11 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Ferme la fenetre de compatibilite 5a/5b : `Response.item` passe NOT NULL et
    `card_value` disparait. IRREVERSIBLE SUR UNE BASE PEUPLEE.

    Django sait ecrire le sens arriere (`AddField` pour `card_value`, `AlterField`
    pour repasser `item` nullable), mais rejouer ce sens arriere ne repeuplerait
    PAS `card_value` : la colonne renaitrait vide (defaut ""), aucune migration en
    aval ne recopie plus `payload["card"]` dedans depuis que le front a bascule.
    Le test de migration ne traverse le sens arriere que sur une base vide : il ne
    dit RIEN de ce cas, exactement comme pour 0012_drop_subject.

    En prod, revenir en arriere = restaurer une sauvegarde anterieure a cette
    migration, pas `migrate rooms 0015`.

    Pas de defaut fourni pour `item` (`makemigrations` proposait d'en inventer un
    pour les lignes NULL existantes ; refuse ici) : depuis 0011, tout round porte
    un item, et 0014 a deja rattache chaque reponse existante au sien. Une ligne
    qui echapperait a cet invariant doit faire echouer la migration, pas se voir
    attribuer un item arbitraire.
    """

    dependencies = [
        ('rooms', '0015_response_item_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='card_value',
        ),
        migrations.AlterField(
            model_name='response',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='rooms.item'),
        ),
    ]
