# Generated by Django 6.0.7 on 2026-09-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0016_drop_card_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
