# Generated by Django 6.0.7 on 2026-09-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0017_round_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='sequence',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
