# Generated by Django 6.0.7 on 2026-09-12 05:23
"""Chainage entre rounds (design 2026-09-11 section7, tache 1 livraison 5e).

Schema seul : aucune ecriture de donnees, donc identique sur sqlite et
PostgreSQL. `source_round` est SET_NULL -- pas CASCADE -- parce que le
chainage (tache suivante) copie des items dans le round consommateur ; une
fois la copie faite, elle lui appartient. Supprimer la source ne doit donc pas
emporter un round deja joue.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0019_backfill_round_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='source_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chained_rounds', to='rooms.round'),
        ),
        migrations.AddField(
            model_name='round',
            name='source_rule',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
