# Generated by Django 6.0.7 on 2026-09-12 05:49
"""Round de correction 1 sur le chainage (design 2026-09-11 §7, tache 2
livraison 5e).

Schema seul : aucune ecriture de donnees, donc identique sur sqlite et
PostgreSQL.

- `Round.source_resolved_at` remplace un signal d'idempotence qui lisait
  l'etat des items (`origin_item` non nul) -- faux positif sur un round
  REJOUE, dont les items portent deja une origine sans rapport avec une
  liaison posee ensuite.
- `Item.source_item` porte le parent DIRECT d'une copie de chainage, distinct
  de `origin_item` qui remonte toujours a la racine de la chaine -- sans les
  deux, l'UI ne peut pas dire "copie depuis le round precedent" sur une
  chaine de plus d'un maillon.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0020_round_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='source_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_items', to='rooms.item'),
        ),
        migrations.AddField(
            model_name='round',
            name='source_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
